// <auto-generated />
using System;
using Banco_VVBA.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Banco_VVBA.Migrations
{
    [DbContext(typeof(BancoVVBAContext))]
    [Migration("20190515143400_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Banco_VVBA.Models.Account_Has_Commissions", b =>
                {
                    b.Property<int>("AccountsHasCommissionsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<int>("CommissionId");

                    b.HasKey("AccountsHasCommissionsId");

                    b.HasIndex("AccountId");

                    b.HasIndex("CommissionId");

                    b.ToTable("Account_Has_Commissions");
                });

            modelBuilder.Entity("Banco_VVBA.Models.CommissionsViewModel", b =>
                {
                    b.Property<int>("CommissionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<double>("Price");

                    b.HasKey("CommissionId");

                    b.ToTable("Commissions");
                });

            modelBuilder.Entity("Banco_VVBA.Models.OperationsViewModel", b =>
                {
                    b.Property<int>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<double>("Amount");

                    b.Property<string>("Concept")
                        .IsRequired();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Message");

                    b.HasKey("OperationId");

                    b.HasIndex("AccountId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("Banco_VVBA.Models.UserAccountsViewModel", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Balance");

                    b.Property<string>("IBAN")
                        .IsRequired();

                    b.Property<int>("UserId");

                    b.HasKey("AccountId");

                    b.HasIndex("IBAN")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Banco_VVBA.Models.UserTypeAccessViewModel", b =>
                {
                    b.Property<int>("TypeAccessId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("TypeAccessId");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("UsersTypeAccess");
                });

            modelBuilder.Entity("Banco_VVBA.Models.UsersViewModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(6);

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("SurnameName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Telephone");

                    b.Property<int>("TypeAccessId");

                    b.HasKey("UserId");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("Mail")
                        .IsUnique();

                    b.HasIndex("TypeAccessId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Banco_VVBA.Models.Account_Has_Commissions", b =>
                {
                    b.HasOne("Banco_VVBA.Models.UserAccountsViewModel", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Banco_VVBA.Models.CommissionsViewModel", "Commission")
                        .WithMany()
                        .HasForeignKey("CommissionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Banco_VVBA.Models.OperationsViewModel", b =>
                {
                    b.HasOne("Banco_VVBA.Models.UserAccountsViewModel", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Banco_VVBA.Models.UserAccountsViewModel", b =>
                {
                    b.HasOne("Banco_VVBA.Models.UsersViewModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Banco_VVBA.Models.UsersViewModel", b =>
                {
                    b.HasOne("Banco_VVBA.Models.UserTypeAccessViewModel", "TypeAccess")
                        .WithMany()
                        .HasForeignKey("TypeAccessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
